name: fitcall
description: "Binay Akademi Mobil Uygulama"
publish_to: 'none' 
version: 2.6.3+23
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  device_info_plus: ^12.1.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^7.0.1
  syncfusion_flutter_calendar: ^31.1.19
  data_table_2: ^2.6.0
  in_app_update: ^4.2.3
  package_info_plus: ^9.0.0
  flutter_native_splash: ^2.4.6
  table_calendar: ^3.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  # adaptive_icon_foreground: "assets/adaptive_foreground.png"
  # adaptive_icon_background: "assets/adaptive_background.png"

flutter_native_splash:
  ios: true
  android: true
  color: "#FFFFFF"   # arka plan
  image: "assets/images/logo.png"
