name: fitcall
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  intl: ^0.20.2
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.2.2
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^6.0.5
  syncfusion_flutter_calendar: ^29.1.38
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  # adaptive_icon_foreground: "assets/adaptive_foreground.png"
  # adaptive_icon_background: "assets/adaptive_background.png"
